### ISSUE TITLE
Yate's correction factor

### ISSUE THREAD

**Issue by dafrenchyman** [MavericksDS/pycorr#2]
I could be totally wrong on this, but should you be using the Yate's correction factor on a 2x2 matrix? Since you've already introduced the bias correction factor into Cramer's V.

I feel like the call to: `stats.chi2_contingency(crosstab_matrix)`
should be : `stats.chi2_contingency(crosstab_matrix, correction=False)` if we have a 2x2.

If I submit something that's perfectly correlated, I seem to get results closer to 1. If I leave it at the default `True` the results are further from 1.

**Comment by anuragithub** [comment]
@dafrenchyman You're observation is correct. The bias correction significantly outperforms normal results, for larger matrices ( bigger than 2*2 ). It was missed while computing. Do you mind raising a PR ?

**Comment by dafrenchyman** [comment]
PR here: https://github.com/MavericksDS/pycorr/pull/3

**Comment by anuragithub** [comment]
Released under [v0.1.5](https://github.com/MavericksDS/pycorr/releases/tag/v0.1.5)
